export const kadraMedicalDataArray = {
  masazysci: [
    // {
    //   nazwisko: "Rypalla",
    //   name: "Dominika",
    //   opis: "",
    //   funkcja: "Masażystka",
    //   fotoPathKoncowka: "rypalla-dominika",
    //   socialMediaLinks: {
    //     facebook: "https://www.facebook.com/dominika.rypalla",
    //   },
    // },
    {
      nazwisko: "Judycka",
      name: "Kamila",
      opis: "",
      funkcja: "Masażystka",
      fotoPathKoncowka: "judycka-kamila",
      socialMediaLinks: {},
    },
  ],
  fizjoterapeuci: [
    // {
    //   nazwisko: "Meisner",
    //   name: "Iwona",
    //   opis: "",
    //   funkcja: "Fizjoterapeutka",
    //   fotoPathKoncowka: "meisner-iwona",
    //   socialMediaLinks: { facebook: "https://www.facebook.com/iwona.meisner" },
    // },
    {
      nazwisko: "Kowalczyk",
      name: "Patrycja",
      opis: "",
      funkcja: "Fizjoterapeutka",
      fotoPathKoncowka: "kowalczyk-patrycja",
      socialMediaLinks: {},
    },
    {
      nazwisko: "Bruździńska",
      name: "Adrianna",
      opis: "",
      funkcja: "Fizjoterapeutka",
      fotoPathKoncowka: "bruzdzinska-adriana",
      socialMediaLinks: {},
    },
    {
      nazwisko: "Horbijczuk",
      name: "Ania",
      opis: "",
      funkcja: "Fizjoterapeutka",
      fotoPathKoncowka: "horbijczuk-ania",
      socialMediaLinks: {},
    },
  ],
  lekarze: [
    {
      nazwisko: "Rogowski",
      name: "Jakub",
      opis: "Absolwent Wydziału Wojskowo-Lekarskiego Uniwersytetu Medycznego w Łodzi. Współpracuje z zespołem Zachar Trening Grup, zapewniając opiekę medyczną i konsultacje dla zawodników wyższych grup treningowych. Swoje doświadczenie rozwija poprzez pracę w różnych środowiskach medycznych, uczestnictwo w kursach i konferencjach naukowych.",
      funkcja: "Lekarz specjalista Traumatologii & ortopedii narządu ruchu",
      fotoPathKoncowka: "rogowski-jakub",
      socialMediaLinks: {},
    },
    {
      nazwisko: "Ciekalski",
      name: "Wiktor",
      opis: "Ortopeda, absolwent Śląskiego Uniwersytetu Medycznego w Zabrzu. Specjalizuje się w diagnostyce i leczeniu schorzeń układu ruchu. Prywatnie pasjonat sportu i aktywnego trybu życia, co przekłada się na jego holistyczne podejście do pacjentów i zrozumienie potrzeb osób trenujących.",
      funkcja: "Lekarz",
      fotoPathKoncowka: "ciekalski-wiktor",
      socialMediaLinks: {},
    },
    {
      nazwisko: "Gadecki",
      name: "Kamil",
      opis: "Lekarz w trakcie specjalizacji z ortopedii i traumatologii narządu ruchu. Absolwent Śląskiego Uniwersytetu Medycznego. W swojej pracy koncentruje się na diagnostyce i leczeniu urazów oraz schorzeń narządu ruchu, łącząc wiedzę kliniczną z nowoczesnym podejściem do rehabilitacji i profilaktyki urazów.",
      funkcja: "Lekarz",
      fotoPathKoncowka: "gadecki-kamil",
      socialMediaLinks: {},
    },
  ],
};
