export const kadraMedicalDataArray = {
  masazysci: [
    // {
    //   nazwisko: "Rypalla",
    //   name: "Dominika",
    //   opis: "",
    //   funkcja: "Masażystka",
    //   fotoPathKoncowka: "rypalla-dominika",
    //   socialMediaLinks: {
    //     facebook: "https://www.facebook.com/dominika.rypalla",
    //   },
    // },
    {
      nazwisko: "Judycka",
      name: "Kamila",
      opis: "",
      funkcja: "Masażystka",
      fotoPathKoncowka: "judycka-kamila",
      socialMediaLinks: {},
    },
  ],
  fizjoterapeuci: [
    // {
    //   nazwisko: "Meisner",
    //   name: "Iwona",
    //   opis: "",
    //   funkcja: "Fizjoterapeutka",
    //   fotoPathKoncowka: "meisner-iwona",
    //   socialMediaLinks: { facebook: "https://www.facebook.com/iwona.meisner" },
    // },
    {
      nazwisko: "Kowalczyk",
      name: "Patrycja",
      opis: "",
      funkcja: "Fizjoterapeutka",
      fotoPathKoncowka: "kowalczyk-patrycja",
      socialMediaLinks: {},
    },
    {
      nazwisko: "Bruździńska",
      name: "Adrianna",
      opis: "",
      funkcja: "Fizjoterapeutka",
      fotoPathKoncowka: "bruzdzinska-adriana",
      socialMediaLinks: {},
    },
    {
      nazwisko: "Horbijczuk",
      name: "Ania",
      opis: "",
      funkcja: "Fizjoterapeutka",
      fotoPathKoncowka: "horbijczuk-ania",
      socialMediaLinks: {},
    },
  ],
  lekarze: [
    {
      nazwisko: "Rogowski",
      name: "Jakub",
      opis: "psum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop pub psum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop pub",
      funkcja: "Lekarz specjalista Traumatologii & ortopedii narządu ruchu",
      fotoPathKoncowka: "rogowski-jakub",
      socialMediaLinks: {},
    },
    {
      nazwisko: "Ciekalski",
      name: "Wiktor",
      opis: "psum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop pub psum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop pub",
      funkcja: "Lekarz",
      fotoPathKoncowka: "ciekalski-wiktor",
      socialMediaLinks: {},
    },
    {
      nazwisko: "Gadecki",
      name: "Kamil",
      opis: "psum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop pub psum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop pub",
      funkcja: "Lekarz",
      fotoPathKoncowka: "gadecki-kamil",
      socialMediaLinks: {},
    },
  ],
};
