export const kadraMedicalDataArray = {
  masazysci: [
    // {
    //   nazwisko: "Rypalla",
    //   name: "Dominika",
    //   opis: "testowy opis",
    //   funkcja: "Masażystka",
    //   fotoPathKoncowka: "rypalla-dominika",
    //   socialMediaLinks: {
    //     facebook: "https://www.facebook.com/dominika.rypalla",
    //   },
    // },
    {
      nazwisko: "Judycka",
      name: "Kamila",
      opis: "testowy opis",
      funkcja: "Masażystka",
      fotoPathKoncowka: "judycka-kamila",
      socialMediaLinks: {},
    },
  ],
  fizjoterapeuci: [
    // {
    //   nazwisko: "Meisner",
    //   name: "Iwona",
    //   opis: "testowy opis",
    //   funkcja: "Fizjoterapeutka",
    //   fotoPathKoncowka: "meisner-iwona",
    //   socialMediaLinks: { facebook: "https://www.facebook.com/iwona.meisner" },
    // },
    {
      nazwisko: "Kowalczyk",
      name: "Patrycja",
      opis: "testowy opis",
      funkcja: "Fizjoterapeutka",
      fotoPathKoncowka: "kowalczyk-patrycja",
      socialMediaLinks: {},
    },
    {
      nazwisko: "Bruździńska",
      name: "Adrianna",
      opis: "testowy opis",
      funkcja: "Fizjoterapeutka",
      fotoPathKoncowka: "bruzdzinska-adriana",
      socialMediaLinks: {},
    },
    {
      nazwisko: "Horbijczuk",
      name: "Ania",
      opis: "testowy opis",
      funkcja: "Fizjoterapeutka",
      fotoPathKoncowka: "horbijczuk-ania",
      socialMediaLinks: {},
    },
  ],
  lekarze: [
    {
      nazwisko: "Rogowski",
      name: "Jakub",
      opis: "testowy opis",
      funkcja: "Lekarz specjalista Traumatologii & ortopedii narządu ruchu",
      fotoPathKoncowka: "rogowski-jakub",
      socialMediaLinks: {},
    },
    {
      nazwisko: "Ciekalski",
      name: "Wiktor",
      opis: "testowy opis",
      funkcja: "Lekarz",
      fotoPathKoncowka: "ciekalski-wiktor",
      socialMediaLinks: {},
    },
    {
      nazwisko: "Gadecki",
      name: "Kamil",
      opis: "testowy opis",
      funkcja: "Lekarz",
      fotoPathKoncowka: "gadecki-kamil",
      socialMediaLinks: {},
    },
  ],
};
