export const kadraFitnessDataArray = {
  manager: [
    {
      nazwisko: "Liminowicz",
      name: "Marta",
      opis: "",
      funkcja: "Manager Klubu",
      fotoPathKoncowka: "liminowicz-marta",
      socialMediaLinks: { email: "manager@infiniti-fit.pl" },
    },
  ],
  recepcja: [
    {
      nazwisko: "Rosa",
      name: "Sandra",
      opis: "",
      funkcja: "Kierownik Recepcji",
      fotoPathKoncowka: "rosa-sandra",
      socialMediaLinks: { email: "info@infiniti-fit.pl" },
    },
    {
      nazwisko: "Bator",
      name: "Monika",
      opis: "",
      funkcja: "Opiekun Recepcji",
      fotoPathKoncowka: "bator-monika",
      socialMediaLinks: { email: "info@infiniti-fit.pl" },
    },
    {
      nazwisko: "Czerska",
      name: "Iza",
      opis: "",
      funkcja: "Opiekun Recepcji",
      fotoPathKoncowka: "czerska-iza",
      socialMediaLinks: { email: "info@infiniti-fit.pl" },
    },
    // {
    //   nazwisko: " Ładak",
    //   name: "Emilia",
    //   opis: "",
    //   funkcja: "Opiekun Recepcji",
    //   fotoPathKoncowka: "ladak-emilia",
    //   socialMediaLinks: { email: "info@infiniti-fit.pl" },
    // },
    {
      nazwisko: "Cholewa",
      name: "Zuzanna",
      opis: "",
      funkcja: "Opiekun Recepcji",
      fotoPathKoncowka: "cholewa-zuzanna",
      socialMediaLinks: { email: "info@infiniti-fit.pl" },
    },
    {
      nazwisko: "Klama",
      name: "Anna",
      opis: "",
      funkcja: "Opiekun Recepcji",
      fotoPathKoncowka: "no-image",
      socialMediaLinks: { email: "info@infiniti-fit.pl" },
    },
    {
      nazwisko: "Kołtun",
      name: "India",
      opis: "",
      funkcja: "Opiekun Recepcji",
      fotoPathKoncowka: "no-image",
      socialMediaLinks: { email: "info@infiniti-fit.pl" },
    },
  ],
  trenerzy: [
    // {
    //   nazwisko: "Agarkova",
    //   name: "Alina",
    //   opis: "",
    //   funkcja: "Instruktor Fitness",
    //   fotoPathKoncowka: "agarkova-alina",
    //   socialMediaLinks: { facebook: "https://www.facebook.com/agarkova.alina" },
    // },
    {
      nazwisko: "Bizoń",
      name: "Adam",
      opis: "",
      funkcja: "Trener MMA i BJJ",
      fotoPathKoncowka: "bizon-adam",
      socialMediaLinks: {
        facebook: "https://www.facebook.com/profile.php?id=100057168981507",
      },
    },
    // {
    //   nazwisko: "Blak",
    //   name: "Julita",
    //   opis: "",
    //   funkcja: "Instruktor Fitness",
    //   fotoPathKoncowka: "blak-julita",
    //   socialMediaLinks: {
    //     facebook: "https://www.facebook.com/julita.blak",
    //   },
    // },
    {
      nazwisko: "Deierling",
      name: "Arek",
      opis: "",
      funkcja: "Instruktor fitness / Trener personalny",
      fotoPathKoncowka: "deierling-arek",
      socialMediaLinks: {
        instagram: "https://www.instagram.com/panie_arku/?hl=pl",
        facebook: "https://www.facebook.com/arkadiusz.deierling",
      },
    },
    {
      nazwisko: "Duma-Majewicz",
      name: "Ania",
      opis: "",
      funkcja: "Instruktor fitness",
      fotoPathKoncowka: "duma-ania",
      socialMediaLinks: { facebook: "https://www.facebook.com/ania.wn.9" },
    },
    {
      nazwisko: "Gidel",
      name: "Ela",
      opis: "",
      funkcja: "Instruktor fitness",
      fotoPathKoncowka: "gidel-ela",
      socialMediaLinks: {
        facebook: "https://www.facebook.com/elagidel",
      },
    },
    {
      nazwisko: "Gołębiowski",
      name: "Romek",
      opis: "",
      funkcja: "Instruktor fitness",
      fotoPathKoncowka: "golebiowski-roman",
      socialMediaLinks: {
        facebook: "https://www.facebook.com/profile.php?id=100000996505827",
      },
    },
    {
      nazwisko: "Grabowska",
      name: "Wioletta",
      opis: "",
      funkcja: "Instruktor fitness",
      fotoPathKoncowka: "grabowska-wioletta",
      socialMediaLinks: {},
    },

    // {
    //   nazwisko: "Kaczmarczyk",
    //   name: "Sebastian",
    //   opis: "",
    //   funkcja: "Instruktor fitness / Trener personalny",
    //   fotoPathKoncowka: "kaczmarczyk-sebastian",
    //   socialMediaLinks: {
    //     facebook: "",
    //   },
    // },
    {
      nazwisko: "Kopacz",
      name: "Izabela",
      opis: "",
      funkcja: "Instruktor fitness",
      fotoPathKoncowka: "kopacz-izabela",
      socialMediaLinks: {
        facebook: "https://www.facebook.com/izabela.kopacz.7",
      },
    },
    // {
    //   nazwisko: "Kubicka",
    //   name: "Katrin",
    //   opis: "",
    //   funkcja: "Instruktor fitness",
    //   fotoPathKoncowka: "kubicka-katrin",
    //   socialMediaLinks: {
    //     facebook: "https://www.facebook.com/profile.php?id=100063105468123",
    //   },
    // },
    {
      nazwisko: "Kuśnierz-Pierz",
      name: "Ania",
      opis: "",
      funkcja: "Instruktor fitness",
      fotoPathKoncowka: "kusnierz-pierz-anna",
      socialMediaLinks: {
        facebook: "https://www.facebook.com/pierz.anka",
      },
    },

    {
      nazwisko: "Kwaśnik Czernicka",
      name: "Agnieszka",
      opis: "",
      funkcja: "Instruktor fitness",
      fotoPathKoncowka: "kwasnik-czernicka-agnieszka",
      socialMediaLinks: {
        facebook: "https://www.facebook.com/agnieszka.kwasnik.351",
      },
    },
    {
      nazwisko: "Mróz",
      name: "Maciej",
      opis: "",
      funkcja: "Instruktor fitness",
      fotoPathKoncowka: "mroz-maciej",
      socialMediaLinks: {
        facebook: "https://www.facebook.com/profile.php?id=100063527531675",
      },
    },
    {
      nazwisko: "Piotrowicz-Kurelowska",
      name: "Ramona",
      opis: "",
      funkcja: "Instruktor fitness",
      fotoPathKoncowka: "piotrowicz-kurelowska-ramona",
      socialMediaLinks: {
        facebook: "https://www.facebook.com/ramonatrenerzdrowia",
      },
    },

    // {
    //   nazwisko: "Prokop",
    //   name: "Piotrek",
    //   opis: "",
    //   funkcja: "Instruktor fitness",
    //   fotoPathKoncowka: "prokop-piotr",
    //   socialMediaLinks: {
    //     facebook: "https://www.facebook.com/prokopiotrek",
    //   },
    // },
    // {
    //   nazwisko: "Rypalla",
    //   name: "Dominika",
    //   opis: "",
    //   funkcja: "Instruktor fitness / Trener personalny",
    //   fotoPathKoncowka: "rypalla-dominika",
    //   socialMediaLinks: {
    //     facebook: "https://www.facebook.com/dominika.rypalla",
    //   },
    // },
    // {
    //   nazwisko: "Saska",
    //   name: "Tomasz",
    //   opis: "",
    //   funkcja: "Instruktor fitness / Trener personalny / Dietetyk",
    //   fotoPathKoncowka: "saska-tomasz",
    //   socialMediaLinks: {
    //     facebook: "https://www.facebook.com/fabrykaformywroclaw",
    //   },
    // },
  ],
};
